;(function () {
;(function () {
(function(){if(!window.b24form){window.b24form=function(e){b24form.forms=b24form.forms||[];b24form.forms.push(e);if(e.ref&&b24form.Loader&&!this.loaded){this.loaded=true;b24form.Loader.loadJs(e.ref,true)}}}if(window.b24form.Loader){return}function e(){this.requested=false;this.queue=[]}e.prototype={run:function(e){e=e||{};var o=e.resources||{};this.queue.push(e.form);if(!this.requested){var t=this.loadApp.bind(this,o.app);this.requested=true;if(o.polyfill&&!this.checkPolyfills()){this.loadJs(o.polyfill,true,t)}else{t()}}this.loadForms()},loadApp:function(e){if(!e){return}window.b24form.App?this.loadForms():this.loadJs(e,true,this.loadForms.bind(this))},loadForms:function(){if(!this.checkPolyfills()){return}if(!window.b24form.App){return}var e=this.queue;this.queue=[];e.forEach(this.loadForm,this)},loadForm:function(e){b24form.App.initFormScript24(e)},checkPolyfills:function(){return window.fetch&&window.Request&&window.Response&&window.Promise&&Object.assign&&Array.prototype.find&&Array.prototype.includes},loadJs:function(e,o,t){var i=document.createElement("SCRIPT");i.setAttribute("type","text/javascript");i.setAttribute("async","");if(o){i.setAttribute("src",e+"?"+(Date.now()/864e5|0));if(t){i.onload=t}this.appendToHead(i)}else{i.appendChild(document.createTextNode(e));this.appendToHead(i)}},appendToHead:function(e){(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(e)}};window.b24form.Loader=new e})();
//# sourceMappingURL=https://b24-kzelfj.bitrix24.com.br/bitrix/js/crm/site/form/embed/unit/script.map.js

window.b24form.Loader.run({"form":{"id":"5","sec":"6gdolw","lang":"br","address":"https:\/\/b24-kzelfj.bitrix24.com.br","views":{"click":{"type":"panel","position":"right","vertical":"bottom"},"auto":{"type":"popup","position":"center","vertical":"bottom","delay":5}},"data":{"language":"br","design":{"font":{"uri":"https:\/\/fonts.googleapis.com\/css?family=Open+Sans","family":"Open Sans"},"border":{"bottom":false,"top":false,"left":false,"right":false},"color":{"primary":"#cb3337ff","primaryText":"#ffffffff","text":"#000000ff","background":"#ffffffff","fieldBorder":"#00000019","fieldBackground":"#00000019","fieldFocusBackground":"#ffffffff"}},"title":"","desc":"","buttonCaption":"Enviar","useSign":true,"date":{"dateFormat":"DD\/MM\/YYYY","dateTimeFormat":"DD\/MM\/YYYY HH:MI:SS","sundayFirstly":false},"currency":{"code":"BRL","title":"Brazilian Real","format":"R$#"},"fields":[{"id":"CONTACT_NAME","name":"CONTACT_NAME","label":"Nome","visible":true,"required":false,"multiple":false,"type":"name","placeholder":null,"value":"","items":[],"bigPic":false,"contentTypes":null},{"id":"CONTACT_EMAIL","name":"CONTACT_EMAIL","label":"E-mail","visible":true,"required":true,"multiple":false,"type":"email","placeholder":null,"value":"","items":[],"bigPic":false,"contentTypes":null}],"agreements":[],"dependencies":[],"recaptcha":{"use":false}}},"resources":{"app":"https:\/\/cdn.bitrix24.com.br\/b17850427\/crm\/form\/app.js","polyfill":"https:\/\/cdn.bitrix24.com.br\/b17850427\/crm\/form\/polyfill.js"}});
})();


})();